version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
    groups:
      prod-dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
    groups:
      github-actions:
        patterns:
          - "*"
