import path from "node:path";
import type { DoctorReport } from "../../report/types.js";
import { runtimeLayouts, type RuntimeName } from "../../runtime/types.js";
import { pathExists, readText, resolveSafePath } from "../../utils/fs.js";
import type { ResolvedWorkspace } from "../../workspace/types.js";
import { pushDoctorWarning } from "./reporting.js";

// Banner Maestro <= 0.5 wrote at the top of the CLAUDE.md it generated.
const legacyGeneratedClaudeMdBanner = "<!-- Generated by Maestro.";
const agentsMdSupportUrl = "https://code.claude.com/docs/en/memory#agents-md";

function getRequiredRuntimePaths(
  workspaceRoot: string,
  runtime: RuntimeName,
  resolvedWorkspace: ResolvedWorkspace,
): string[] {
  const projection = resolvedWorkspace.runtimes[runtime];
  const layout = runtimeLayouts[runtime];
  const required: string[] = [];

  if (projection?.skills && layout.skills) {
    required.push(resolveSafePath(workspaceRoot, layout.skills, `${runtime} skills directory`));
  }
  if (projection?.agents && resolvedWorkspace.selectedAgents[runtime].length > 0) {
    required.push(resolveSafePath(workspaceRoot, layout.agents.dir, `${runtime} agents directory`));
  }
  if (projection?.workflows && layout.workflows && resolvedWorkspace.selectedWorkflows.length > 0) {
    required.push(
      resolveSafePath(workspaceRoot, layout.workflows, `${runtime} workflows directory`),
    );
  }

  return required;
}

export async function runRuntimeArtifactChecks(
  workspaceRoot: string,
  resolvedWorkspace: ResolvedWorkspace,
  report: DoctorReport,
): Promise<void> {
  for (const runtime of Object.keys(resolvedWorkspace.runtimes) as RuntimeName[]) {
    for (const requiredPath of getRequiredRuntimePaths(workspaceRoot, runtime, resolvedWorkspace)) {
      if (!(await pathExists(requiredPath))) {
        pushDoctorWarning(report, {
          code: "RUNTIME_ARTIFACT_MISSING",
          message: `Runtime artifact is missing for ${runtime}.`,
          path: requiredPath,
        });
      }
    }
  }

  await checkLegacyGeneratedClaudeMd(workspaceRoot, report);
}

/**
 * A CLAUDE.md left over from Maestro <= 0.5 carries no instructions of its own, yet its
 * presence stops Claude Code from reading AGENTS.md.
 */
async function checkLegacyGeneratedClaudeMd(
  workspaceRoot: string,
  report: DoctorReport,
): Promise<void> {
  const claudeMdPath = path.join(workspaceRoot, "CLAUDE.md");
  if (!(await pathExists(claudeMdPath))) {
    return;
  }

  if ((await readText(claudeMdPath)).startsWith(legacyGeneratedClaudeMdBanner)) {
    pushDoctorWarning(report, {
      code: "LEGACY_GENERATED_CLAUDE_MD",
      message: `CLAUDE.md was generated by an earlier Maestro version and hides AGENTS.md from Claude Code. Delete it, or replace its content with "@AGENTS.md". See ${agentsMdSupportUrl}.`,
      path: claudeMdPath,
    });
  }
}
