import { mkdir } from "node:fs/promises";
import path from "node:path";
import YAML from "yaml";
import type { RuntimeName } from "../../runtime/types.js";
import type { WorkspaceManifest } from "../../workspace/types.js";
import { pathExists, readText, writeText } from "../../utils/fs.js";
import { getFrameworkRange } from "../../version.js";
import { renderWorkspaceDescriptor, workspaceDescriptorFileName } from "../workspace-descriptor.js";
import { renderDefaultWorkspaceGitignore } from "../workspace-gitignore.js";
import { workspaceManifestFileName } from "../workspace-manifest.js";

const defaultRuntimeSelection: RuntimeName[] = ["codex", "claude-code"];
const maestroInstallGuideUrl = "https://github.com/Th3Mouk/maestro/blob/main/docs/cli/install.md";
const maestroReadmeSectionMarker = "This project uses Maestro to manage the workspace.";

export async function initWorkspace(
  targetDirectory: string,
  options: { dryRun?: boolean; runtimeNames?: RuntimeName[] } = {},
): Promise<void> {
  const dryRun = options.dryRun ?? false;
  const workspaceRoot = path.resolve(targetDirectory);
  if (!dryRun) {
    await mkdir(workspaceRoot, { recursive: true });
  }

  const selectedRuntimeNames = options.runtimeNames ?? defaultRuntimeSelection;
  const runtimes = Object.fromEntries(
    selectedRuntimeNames.map((runtimeName) => [runtimeName, runtimeConfigFor(runtimeName)]),
  ) as NonNullable<WorkspaceManifest["spec"]["runtimes"]>;

  const manifest: WorkspaceManifest = {
    apiVersion: "maestro/v1",
    kind: "Workspace",
    metadata: {
      name: path.basename(workspaceRoot),
      description: "Workspace generated by Maestro.",
    },
    spec: {
      framework: { version: getFrameworkRange() },
      execution: {
        worktrees: {
          enabled: true,
          rootDir: ".maestro/worktrees",
          branchPrefix: "task",
        },
      },
      runtimes,
      repositories: [],
    },
  };

  if (dryRun) {
    return;
  }

  await mkdir(path.join(workspaceRoot, ".maestro"), { recursive: true });
  await writeText(path.join(workspaceRoot, workspaceManifestFileName), YAML.stringify(manifest));
  await writeText(
    path.join(workspaceRoot, "package.json"),
    JSON.stringify(
      {
        name: manifest.metadata.name,
        private: true,
        scripts: {
          "workspace:install": "maestro install",
          "workspace:bootstrap": "maestro bootstrap",
          "workspace:sync": "maestro sync",
          "workspace:update": "maestro update",
          "workspace:doctor": "maestro doctor",
          "workspace:git:checkout": "maestro git checkout",
          "workspace:git:pull": "maestro git pull",
          "workspace:git:sync": "maestro git sync",
        },
        dependencies: {
          maestro: getFrameworkRange(),
        },
      },
      null,
      2,
    ),
  );
  await writeText(
    path.join(workspaceRoot, "README.md"),
    await renderWorkspaceReadme(workspaceRoot, manifest.metadata.name),
  );
  await writeText(
    path.join(workspaceRoot, "AGENTS.md"),
    [
      "# AGENTS.md",
      "",
      "Guide for AI agents operating this Maestro workspace.",
      "",
      "## Core loop",
      "",
      "1. Validate the workspace contract before making changes:",
      "   - `maestro install --workspace . --dry-run`",
      "2. Install or refresh the managed repositories when needed:",
      "   - `maestro install --workspace .`",
      "3. Validate the installed workspace when repositories and projections are present:",
      "   - `maestro doctor --workspace .`",
      "4. Realign and update managed repositories when needed:",
      "   - `maestro git checkout --workspace .`",
      "   - `maestro git pull --workspace .`",
      "   - `maestro git sync --workspace .`",
      "5. Create an isolated task worktree:",
      "   - `maestro worktree --workspace . --task <task-name>`",
      "",
      "## Command map",
      "",
      "- `maestro init <dir>`: scaffold a workspace contract.",
      "- `maestro install --workspace <path>`: initialize the workspace Git repository when needed, create the `🪄 booted by Maestro` commit when the repository is unborn, resolve packs, clone repos, and project runtimes.",
      "- `maestro bootstrap --workspace <path>`: detect and execute repository dependency bootstrap commands.",
      "- `maestro sync --workspace <path>`: reconcile materialized repositories with the manifest.",
      "- `maestro update --workspace <path>`: rerun resolution and regenerate projected artifacts.",
      "- `maestro code-workspace --workspace <path>`: generate the optional editor workspace projection on demand.",
      "- `maestro doctor --workspace <path>`: validate lockfile, remotes, sparse paths, and generated artifacts.",
      "- `maestro git checkout --workspace <path>`: check out each managed repository onto its reference branch.",
      "- `maestro git pull --workspace <path>`: pull the currently checked out branch in each managed repository.",
      "- `maestro git sync --workspace <path>`: check out reference branches, then pull each repository in one pass.",
      "- `maestro worktree --workspace <path> --task <task-name>`: create an isolated worktree for one task.",
      "",
      "## Consumption",
      "",
      `- Read \`${workspaceDescriptorFileName}\` when an agent, harness, or script needs a neutral view of the workspace.`,
      "- Open the workspace root in JetBrains, VS Code, or another IDE to work in the full materialized folder.",
      "- Open `maestro.code-workspace` only when you want an explicit multi-root projection in a compatible editor.",
      "- Managed repositories are materialized under `repos/<name>`.",
      "- Project-scoped MCP servers declared in `maestro.yaml` are projected into `.codex/config.toml` and `.mcp.json`.",
      "- Native plugin bundles stay in `plugins/`; Maestro does not re-encode their internals in the manifest.",
      "",
      "## Guardrails",
      "",
      "- Keep edits within allowed paths and repository sparse surfaces.",
      "- Prefer one task per worktree for clean review and rollback.",
      "- Use dry-run modes first when available before destructive operations.",
    ].join("\n"),
  );
  await writeText(path.join(workspaceRoot, ".gitignore"), renderDefaultWorkspaceGitignore());
  await writeText(
    path.join(workspaceRoot, workspaceDescriptorFileName),
    renderWorkspaceDescriptor({
      execution: manifest.spec.execution,
      runtimeNames: Object.entries(manifest.spec.runtimes)
        .filter(([, config]) => config?.enabled)
        .map(([runtime]) => runtime as RuntimeName),
      workspaceName: manifest.metadata.name,
      repositories: manifest.spec.repositories,
    }),
  );
}

function runtimeConfigFor(runtimeName: RuntimeName) {
  switch (runtimeName) {
    case "codex":
      return {
        enabled: true,
        installProjectConfig: true,
        installAgents: true,
        useAgentsFile: "AGENTS.md",
      };
    case "claude-code":
      return {
        enabled: true,
        installProjectInstructions: true,
        instructionsFile: "CLAUDE.md",
      };
    case "opencode":
      return {
        enabled: true,
        installProjectConfig: true,
        projectConfigPath: ".opencode/opencode.json",
      };
  }
}

async function renderWorkspaceReadme(
  workspaceRoot: string,
  workspaceName: string,
): Promise<string> {
  const readmePath = path.join(workspaceRoot, "README.md");
  const baseReadme = [
    `# ${workspaceName}`,
    "",
    "Workspace initialized by Maestro.",
    "",
    "This repository versions the workspace contract and the generated workspace descriptor.",
    "Add repositories to `maestro.yaml`, then run `maestro install --workspace .` to initialize the workspace Git repository when needed, create the `🪄 booted by Maestro` commit when the repository is unborn, and materialize them under `repos/`.",
    "",
    "## Workspace contract",
    "",
    `- \`${workspaceDescriptorFileName}\` is the canonical workspace descriptor for agents, harnesses, and scripts.`,
    "- `AGENTS.md` gives AI agents the Maestro command map for this workspace.",
    "- `maestro.yaml` is the source of truth for repositories, runtimes, execution, and policies.",
    "- `maestro.code-workspace` is optional and can be generated on demand for VS Code multi-root use.",
    "",
    "## Edit these files",
    "",
    "- `maestro.yaml` for the workspace contract.",
    "- `AGENTS.md` for the workspace CLI map.",
    "- `package.json` for workspace scripts.",
    "- `README.md` for the workspace-facing overview.",
    "",
    "## Generated directories",
    "",
    "- `repos/` for materialized repositories.",
    "- `.maestro/` for workspace state and reports.",
    "- `.codex/`, `.claude/`, and `.opencode/` only when the corresponding runtimes are enabled in the manifest.",
  ].join("\n");

  if (!(await pathExists(readmePath))) {
    return `${baseReadme}\n\n${renderMaestroReadmeSection()}\n`;
  }

  const existingReadme = await readText(readmePath);
  if (existingReadme.includes(maestroReadmeSectionMarker)) {
    return existingReadme;
  }

  return appendReadmeSection(existingReadme, renderMaestroReadmeSection());
}

function renderMaestroReadmeSection(): string {
  return [
    "## Maestro",
    "",
    maestroReadmeSectionMarker,
    `Install or update Maestro by following the [CLI install guide](${maestroInstallGuideUrl}).`,
    "After installation, run `maestro install --workspace .` from the workspace root.",
  ].join("\n");
}

function appendReadmeSection(existingContent: string, section: string): string {
  if (existingContent.length === 0) {
    return `${section}\n`;
  }

  const separator = existingContent.endsWith("\n") ? "\n" : "\n\n";
  return `${existingContent}${separator}${section}\n`;
}
