import path from "node:path";
import type { RuntimeProjectionContext, RuntimeProjector } from "../../runtime/types.js";
import type { McpServer } from "../../workspace/types.js";
import { copyDir, ensureDir, removeIfExists, writeJson, writeText } from "../../utils/fs.js";

const generatedBanner = "<!-- Generated by Maestro. Local overrides may exist in overrides/. -->";

class ClaudeCodeProjector implements RuntimeProjector {
  name = "claude-code" as const;

  async project({ workspaceRoot, resolvedWorkspace }: RuntimeProjectionContext) {
    const claudeRoot = path.join(workspaceRoot, ".claude");
    await ensureDir(path.join(claudeRoot, "agents"));
    await ensureDir(path.join(claudeRoot, "commands"));

    for (const agent of resolvedWorkspace.selectedAgents["claude-code"]) {
      await writeText(
        path.join(claudeRoot, "agents", `${agent.name}.${agent.extension}`),
        agent.content,
      );
    }

    const claudeSkillsRoot = path.join(claudeRoot, "skills");
    await removeIfExists(claudeSkillsRoot);
    await ensureDir(claudeSkillsRoot);
    for (const skill of resolvedWorkspace.selectedSkills) {
      await copyDir(skill.root, path.join(claudeSkillsRoot, skill.name));
    }

    await writeText(
      path.join(workspaceRoot, "CLAUDE.md"),
      `${generatedBanner}\n\n# ${resolvedWorkspace.manifest.metadata.name}\n\nWorkspace IA pour Claude Code.\n`,
    );

    const claudePlugins = resolvedWorkspace.manifest.spec.plugins?.["claude-code"];
    await writeJson(path.join(claudeRoot, "settings.json"), {
      generated: true,
      workspace: resolvedWorkspace.manifest.metadata.name,
      ...(claudePlugins?.enabled ? { enabledPlugins: claudePlugins.enabled } : {}),
      ...(claudePlugins?.marketplaces
        ? { extraKnownMarketplaces: claudePlugins.marketplaces }
        : {}),
    });

    const mcpConfigPath = path.join(workspaceRoot, ".mcp.json");
    if (resolvedWorkspace.mcpServers.length === 0) {
      await removeIfExists(mcpConfigPath);
      return;
    }

    await writeJson(mcpConfigPath, {
      mcpServers: Object.fromEntries(
        resolvedWorkspace.mcpServers.map((server) => [server.name, toClaudeMcpServer(server)]),
      ),
    });
  }
}

class StandardProjector implements RuntimeProjector {
  name = "standard" as const;

  async project({ workspaceRoot, resolvedWorkspace }: RuntimeProjectionContext) {
    const agentsRoot = path.join(workspaceRoot, ".agents");

    // Scoped to skills/ and agents/: .agents/plugins/marketplace.json is a separate,
    // hand-authored artifact (see docs/manifests/workspace.md) that must survive projection.
    const skillsRoot = path.join(agentsRoot, "skills");
    await removeIfExists(skillsRoot);
    await ensureDir(skillsRoot);
    for (const skill of resolvedWorkspace.selectedSkills) {
      await copyDir(skill.root, path.join(skillsRoot, skill.name));
    }

    const selectedAgents = resolvedWorkspace.selectedAgents.standard;
    if (selectedAgents.length > 0) {
      const agentsDir = path.join(agentsRoot, "agents");
      await ensureDir(agentsDir);
      for (const agent of selectedAgents) {
        await writeText(path.join(agentsDir, `${agent.name}.${agent.extension}`), agent.content);
      }
    }
  }
}

export function createBuiltInProjectors(): RuntimeProjector[] {
  return [new ClaudeCodeProjector(), new StandardProjector()];
}

function toClaudeMcpServer(server: McpServer): Record<string, unknown> {
  const base: Record<string, unknown> = {};

  if (server.transport === "stdio") {
    base.type = "stdio";
    base.command = server.command;
    if (server.args && server.args.length > 0) {
      base.args = server.args;
    }
    if (server.env && Object.keys(server.env).length > 0) {
      base.env = server.env;
    }
  } else {
    base.type = "http";
    base.url = server.url;
    if (server.httpHeaders && Object.keys(server.httpHeaders).length > 0) {
      base.headers = server.httpHeaders;
    }
  }

  return base;
}
