import path from "node:path";
import type { RuntimeProjectionContext, RuntimeProjector } from "../../runtime/types.js";
import type { McpServer } from "../../workspace/types.js";
import { ensureDir, removeIfExists, writeJson, writeText } from "../../utils/fs.js";

const generatedBanner = "<!-- Generated by Maestro. Local overrides may exist in overrides/. -->";

class CodexProjector implements RuntimeProjector {
  name = "codex" as const;

  async project({ workspaceRoot, resolvedWorkspace }: RuntimeProjectionContext) {
    const codexRoot = path.join(workspaceRoot, ".codex");
    await ensureDir(path.join(codexRoot, "agents"));
    await writeText(
      path.join(codexRoot, "config.toml"),
      renderCodexConfig(
        resolvedWorkspace.manifest.metadata.name,
        resolvedWorkspace.mcpServers,
        resolvedWorkspace.manifest.spec.plugins?.codex?.enabled,
      ),
    );

    for (const agent of resolvedWorkspace.selectedAgents.codex) {
      await writeText(
        path.join(codexRoot, "agents", `${agent.name}.${agent.extension}`),
        agent.content,
      );
    }
  }
}

class ClaudeCodeProjector implements RuntimeProjector {
  name = "claude-code" as const;

  async project({ workspaceRoot, resolvedWorkspace }: RuntimeProjectionContext) {
    const claudeRoot = path.join(workspaceRoot, ".claude");
    await ensureDir(path.join(claudeRoot, "agents"));
    await ensureDir(path.join(claudeRoot, "commands"));

    for (const agent of resolvedWorkspace.selectedAgents["claude-code"]) {
      await writeText(
        path.join(claudeRoot, "agents", `${agent.name}.${agent.extension}`),
        agent.content,
      );
    }

    await writeText(
      path.join(workspaceRoot, "CLAUDE.md"),
      `${generatedBanner}\n\n# ${resolvedWorkspace.manifest.metadata.name}\n\nWorkspace IA pour Claude Code.\n`,
    );

    const claudePlugins = resolvedWorkspace.manifest.spec.plugins?.["claude-code"];
    await writeJson(path.join(claudeRoot, "settings.json"), {
      generated: true,
      workspace: resolvedWorkspace.manifest.metadata.name,
      ...(claudePlugins?.enabled ? { enabledPlugins: claudePlugins.enabled } : {}),
      ...(claudePlugins?.marketplaces
        ? { extraKnownMarketplaces: claudePlugins.marketplaces }
        : {}),
    });

    const mcpConfigPath = path.join(workspaceRoot, ".mcp.json");
    if (resolvedWorkspace.mcpServers.length === 0) {
      await removeIfExists(mcpConfigPath);
      return;
    }

    await writeJson(mcpConfigPath, {
      mcpServers: Object.fromEntries(
        resolvedWorkspace.mcpServers.map((server) => [server.name, toClaudeMcpServer(server)]),
      ),
    });
  }
}

class OpenCodeProjector implements RuntimeProjector {
  name = "opencode" as const;

  async project({ workspaceRoot, resolvedWorkspace }: RuntimeProjectionContext) {
    const opencodeRoot = path.join(workspaceRoot, ".opencode");
    await ensureDir(path.join(opencodeRoot, "agents"));

    for (const agent of resolvedWorkspace.selectedAgents.opencode) {
      await writeText(
        path.join(opencodeRoot, "agents", `${agent.name}.${agent.extension}`),
        agent.content,
      );
    }

    await writeJson(path.join(opencodeRoot, "opencode.json"), {
      generated: true,
      workspace: resolvedWorkspace.manifest.metadata.name,
      skills: {
        paths: [".maestro/skills"],
      },
    });
  }
}

export function createBuiltInProjectors(): RuntimeProjector[] {
  return [new CodexProjector(), new ClaudeCodeProjector(), new OpenCodeProjector()];
}

function renderCodexConfig(
  workspaceName: string,
  mcpServers: McpServer[],
  enabledPlugins?: Record<string, boolean>,
): string {
  const lines = [
    "# Generated by Maestro",
    `[workspace]`,
    `name = ${toTomlString(workspaceName)}`,
    `skills_dir = "skills"`,
  ];

  for (const server of mcpServers) {
    const tableKey = toTomlTableKey(server.name);
    lines.push("");
    lines.push(`[mcp_servers.${tableKey}]`);
    if (server.transport === "stdio") {
      lines.push(`command = ${toTomlString(server.command)}`);
      if (server.args && server.args.length > 0) {
        lines.push(`args = ${toTomlArray(server.args)}`);
      }
      if (server.cwd) {
        lines.push(`cwd = ${toTomlString(server.cwd)}`);
      }
      if (server.envVars && server.envVars.length > 0) {
        lines.push(`env_vars = ${toTomlArray(server.envVars)}`);
      }
    } else {
      lines.push(`url = ${toTomlString(server.url)}`);
      if (server.bearerTokenEnvVar) {
        lines.push(`bearer_token_env_var = ${toTomlString(server.bearerTokenEnvVar)}`);
      }
      if (server.httpHeaders && Object.keys(server.httpHeaders).length > 0) {
        lines.push(`http_headers = ${toTomlInlineTable(server.httpHeaders)}`);
      }
      if (server.envHttpHeaders && Object.keys(server.envHttpHeaders).length > 0) {
        lines.push(`env_http_headers = ${toTomlInlineTable(server.envHttpHeaders)}`);
      }
    }

    if (server.enabled !== undefined) {
      lines.push(`enabled = ${server.enabled}`);
    }
    if (server.required !== undefined) {
      lines.push(`required = ${server.required}`);
    }
    if (server.startupTimeoutSec !== undefined) {
      lines.push(`startup_timeout_sec = ${server.startupTimeoutSec}`);
    }
    if (server.toolTimeoutSec !== undefined) {
      lines.push(`tool_timeout_sec = ${server.toolTimeoutSec}`);
    }
    if (server.enabledTools && server.enabledTools.length > 0) {
      lines.push(`enabled_tools = ${toTomlArray(server.enabledTools)}`);
    }
    if (server.disabledTools && server.disabledTools.length > 0) {
      lines.push(`disabled_tools = ${toTomlArray(server.disabledTools)}`);
    }
    if (server.transport === "stdio" && server.env && Object.keys(server.env).length > 0) {
      lines.push(`[mcp_servers.${tableKey}.env]`);
      for (const [key, value] of Object.entries(server.env).sort(([left], [right]) =>
        left.localeCompare(right),
      )) {
        lines.push(`${toTomlTableKey(key)} = ${toTomlString(value)}`);
      }
    }
  }

  if (enabledPlugins && Object.keys(enabledPlugins).length > 0) {
    for (const [pluginRef, enabled] of Object.entries(enabledPlugins).sort(([left], [right]) =>
      left.localeCompare(right),
    )) {
      lines.push("");
      lines.push(`[plugins.${toTomlString(pluginRef)}]`);
      lines.push(`enabled = ${enabled}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

function toClaudeMcpServer(server: McpServer): Record<string, unknown> {
  const base: Record<string, unknown> = {};

  if (server.transport === "stdio") {
    base.type = "stdio";
    base.command = server.command;
    if (server.args && server.args.length > 0) {
      base.args = server.args;
    }
    if (server.env && Object.keys(server.env).length > 0) {
      base.env = server.env;
    }
  } else {
    base.type = "http";
    base.url = server.url;
    if (server.httpHeaders && Object.keys(server.httpHeaders).length > 0) {
      base.headers = server.httpHeaders;
    }
  }

  return base;
}

function toTomlString(value: string): string {
  return JSON.stringify(value);
}

function toTomlArray(values: string[]): string {
  return `[${values.map((value) => toTomlString(value)).join(", ")}]`;
}

function toTomlInlineTable(value: Record<string, string>): string {
  return `{ ${Object.entries(value)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, entry]) => `${toTomlString(key)} = ${toTomlString(entry)}`)
    .join(", ")} }`;
}

function toTomlTableKey(value: string): string {
  return /^[A-Za-z0-9_-]+$/.test(value) ? value : toTomlString(value);
}
