import path from "node:path";
import type { RuntimeProjectionContext, RuntimeProjector } from "../../runtime/types.js";
import { defaultRuntimeProjectionMode } from "../../workspace/schema.js";
import type {
  McpServer,
  ResolvedAgent,
  ResolvedSkill,
  RuntimeProjectionMode,
} from "../../workspace/types.js";
import { copyDir, ensureDir, removeIfExists, writeJson, writeText } from "../../utils/fs.js";

const generatedBanner = "<!-- Generated by Maestro. Local overrides may exist in overrides/. -->";

// "replace" wipes the whole target directory first so Maestro owns it outright.
// "merge" (the default) only touches entries whose name Maestro is about to project,
// so hand-placed agents/skills that share the directory survive untouched.
async function projectAgents(
  agentsDir: string,
  agents: ResolvedAgent[],
  mode: RuntimeProjectionMode,
  { createIfEmpty = true }: { createIfEmpty?: boolean } = {},
): Promise<void> {
  if (agents.length === 0 && mode === "merge" && !createIfEmpty) {
    return;
  }

  if (mode === "replace") {
    await removeIfExists(agentsDir);
  }
  await ensureDir(agentsDir);

  for (const agent of agents) {
    await writeText(path.join(agentsDir, `${agent.name}.${agent.extension}`), agent.content);
  }
}

async function projectSkills(
  skillsDir: string,
  skills: ResolvedSkill[],
  mode: RuntimeProjectionMode,
): Promise<void> {
  if (mode === "replace") {
    await removeIfExists(skillsDir);
  }
  await ensureDir(skillsDir);

  for (const skill of skills) {
    const targetSkillDir = path.join(skillsDir, skill.name);
    if (mode === "merge") {
      await removeIfExists(targetSkillDir);
    }
    await copyDir(skill.root, targetSkillDir);
  }
}

class ClaudeCodeProjector implements RuntimeProjector {
  name = "claude-code" as const;

  async project({ workspaceRoot, resolvedWorkspace }: RuntimeProjectionContext) {
    const claudeRoot = path.join(workspaceRoot, ".claude");
    const projectionMode =
      resolvedWorkspace.runtimes["claude-code"]?.projectionMode ?? defaultRuntimeProjectionMode;
    await ensureDir(path.join(claudeRoot, "commands"));

    await projectAgents(
      path.join(claudeRoot, "agents"),
      resolvedWorkspace.selectedAgents["claude-code"],
      projectionMode,
    );

    await projectSkills(
      path.join(claudeRoot, "skills"),
      resolvedWorkspace.selectedSkills,
      projectionMode,
    );

    await writeText(
      path.join(workspaceRoot, "CLAUDE.md"),
      `${generatedBanner}\n\n# ${resolvedWorkspace.manifest.metadata.name}\n\nWorkspace IA pour Claude Code.\n`,
    );

    const claudePlugins = resolvedWorkspace.manifest.spec.plugins?.["claude-code"];
    await writeJson(path.join(claudeRoot, "settings.json"), {
      generated: true,
      workspace: resolvedWorkspace.manifest.metadata.name,
      ...(claudePlugins?.enabled ? { enabledPlugins: claudePlugins.enabled } : {}),
      ...(claudePlugins?.marketplaces
        ? { extraKnownMarketplaces: claudePlugins.marketplaces }
        : {}),
    });

    const mcpConfigPath = path.join(workspaceRoot, ".mcp.json");
    if (resolvedWorkspace.mcpServers.length === 0) {
      await removeIfExists(mcpConfigPath);
      return;
    }

    await writeJson(mcpConfigPath, {
      mcpServers: Object.fromEntries(
        resolvedWorkspace.mcpServers.map((server) => [server.name, toClaudeMcpServer(server)]),
      ),
    });
  }
}

class StandardProjector implements RuntimeProjector {
  name = "standard" as const;

  async project({ workspaceRoot, resolvedWorkspace }: RuntimeProjectionContext) {
    const agentsRoot = path.join(workspaceRoot, ".agents");
    const projectionMode =
      resolvedWorkspace.runtimes.standard?.projectionMode ?? defaultRuntimeProjectionMode;

    // Scoped to skills/ and agents/: .agents/plugins/marketplace.json is a separate,
    // hand-authored artifact (see docs/manifests/workspace.md) that must survive projection.
    await projectSkills(
      path.join(agentsRoot, "skills"),
      resolvedWorkspace.selectedSkills,
      projectionMode,
    );

    await projectAgents(
      path.join(agentsRoot, "agents"),
      resolvedWorkspace.selectedAgents.standard,
      projectionMode,
      { createIfEmpty: false },
    );
  }
}

export function createBuiltInProjectors(): RuntimeProjector[] {
  return [new ClaudeCodeProjector(), new StandardProjector()];
}

function toClaudeMcpServer(server: McpServer): Record<string, unknown> {
  const base: Record<string, unknown> = {};

  if (server.transport === "stdio") {
    base.type = "stdio";
    base.command = server.command;
    if (server.args && server.args.length > 0) {
      base.args = server.args;
    }
    if (server.env && Object.keys(server.env).length > 0) {
      base.env = server.env;
    }
  } else {
    base.type = "http";
    base.url = server.url;
    if (server.httpHeaders && Object.keys(server.httpHeaders).length > 0) {
      base.headers = server.httpHeaders;
    }
  }

  return base;
}
