apiVersion: maestro/v1
kind: WorkspaceFragment
metadata:
  name: ops-workspace-packs
spec:
  packs:
    - name: "@maestro/pack-core"
      version: ^0.1.0
      visibility: public
      source: ../packs/pack-core
    - name: "@maestro/pack-github-actions"
      version: ^0.1.0
      visibility: public
      source: ../packs/pack-github-actions
    - name: "@foodpilot/pack-ops-private"
      version: ^0.1.0
      visibility: private
      source: ../packs/pack-private
